name: Web Service CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:     

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: ls
    
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
          command: validate
          arguments: -syntax-only
          workingDir: packer
          target:  ami-create.pkr.hcl

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      