name: Build and Deploy Web server application

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  WEB_SERVER_ARTIFACT_NAME: csye6225-webserver-${{ github.sha }}.zip
 

on:
  pull_request:
    branches: [ temp_main ]

jobs:    
  build_and_deploy:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v1
      - name: Building the Artifact zip file 
        run: |
          echo "Building Zip with name - ${{env.WEB_SERVER_ARTIFACT_NAME}}"
          echo "## Current Working directory ##"
          pwd
          echo "## Listing all contents ##"
          ls -al

    