name: AMI Creation with Packer

on:
  push:
    tags:
      - '*'
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:

  zipcreation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create webservice Folder
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='node_modules/' --exclude='package-lock.json/' --exclude='.gitignore' . ./webservice
      - name: Switch to webservice Folder
        run: |
          zip -r webservice.zip webservice
      - uses: actions/upload-artifact@v1
        with:
          name: webservice.zip
          path: ${{ github.workspace }}/webservice.zip

  packer:
    runs-on: ubuntu-latest
    name: webservice-packer-ami-creation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: "pwd"
      - run: "ls"
      
      - name: Init Webservice Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target:  packer/ami-create.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target:  packer/ami-create.pkr.hcl

     
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Build AMI with Packer
        uses: hashicorp/packer-github-actions@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          command: build
          arguments: " -color=false -on-error=abort"
          target: packer/amiCreateUpgraded.pkr.hcl
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}