name: Webservice ami Creation with Packer

on:
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  packer:
    runs-on: ubuntu-latest
    name: webservice-packer-ami-creation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: "pwd"
      - run: "ls"

       # init  templates
      - name: Init Webservice Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target:  packer/ami-create.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target:  packer/ami-create.pkr.hcl

     
      - run: "export AWS_ACCESS_KEY_ID= ${{ secrets.AWS_ACCESS_KEY_ID }}"
      - run: "export AWS_SECRET_ACCESS_KEY= ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: my-github-actions-role
          role-duration-seconds: 1200
      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          command: build
          arguments: " -color=false -on-error=abort"
          target: packer/amiCreateUpgraded.pkr.hcl
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # additional steps to process artifacts