name: AMI Creation with Packer

on:
  push:
    tags:
      - '*'
    branches: [ temp_main ]

env:
  WEB_SERVER_ARTIFACT_NAME: csye6225-webserver-${{ github.sha }}.zip
  CODE_DEPLOY_APPLICATION_NAME: csye6225-webserver
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:

  zipcreation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create webservice Folder
        run: rsync -arv --exclude='node_modules/' --exclude='.git/' --exclude='.github/' . ./webservice
      - name: Zip files using artifact name
        run: |
          zip -r ${{env.WEB_SERVER_ARTIFACT_NAME}}.zip webservice
      - uses: actions/upload-artifact@v1
        with:
          name: ${{env.WEB_SERVER_ARTIFACT_NAME}}.zip
          path: ${{ github.workspace }}/${{env.WEB_SERVER_ARTIFACT_NAME}}.zip

  packer:
    runs-on: ubuntu-latest
    needs: zipcreation
    steps:  
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with: 
         name: ${{env.WEB_SERVER_ARTIFACT_NAME}}.zip
     
      # Runs a single command using the runners shell
      - name: Build AMI with Packer
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: "packer/amiCreateUpgraded.pkr.hcl"
          workingDir: '.' 
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_CODE_DEPLOY_BUCKET_NAME: ${{ secrets.AWS_CODE_DEPLOY_BUCKET_NAME }} 

      