name: Webservice AMI Creation with Packer

on:
  pull_request:
    branches: [ main ]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: webservice-packer-ami-creation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: "pwd"
      - run: "ls"

       # init  templates
      - name: Init Webservice Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: -syntax-only
          target:  packer/ami-create.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target:  packer/ami-create.pkr.hcl

     

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer/ami-create.pkr.hcl
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # additional steps to process artifacts